language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-26
  - extra
script:
- "./gradlew assembleDebug"

notifications:
  email:
    recipients:
      - secure: "7etAUT2CF+FYDqh0zPaK1qcXdN2Pyy582e1cJl32lK5MGd+pxwgPA69ZU69T128RBHaHllQeOCH2L7IQBbCP+coxBoqZ2HwH74PfppiN+I7OX3LdtVVdrsSTsnl7emIVpbismI1ZeFIMOl1+oKFHpNFUNOlKgWfsOLP9kohnTOXDGOZSiKAD4v8r7nTW+fXopiWLxq+yVtwFI2Akz7kpULQPuRoFl2/cM+0+NGf15+/naW0N3Klh7bsOfoMJ09oGcDwF+ofkK3f5J1ddLhFKma8+bOaQZ9ycOqUr6VuLaNkF/vylFU05/lMBpSxMYjwQGiYpXCZ3BsRKXpkgJsGbV/6PpX+JnT7MvF8i4iZdyUCVZdhVqgkEvLuz4IPrrtoA5nY3bFMC1u5bU2ruFN4r4A0Vc/mXBlhGWBNImDmKqKHaHVAAJbNhXLd+W4PUoytSpCfnDNRuEUm9kz9rRU0fR5o8Bq2e3gCkZUYq0cNcAHi7mSQ/OmKU9WWiQJnAC27EjFUil2HyUds9h0jkLqb1N08i+U+oqEW8JOrE2BV7iSoUaprW0jaPozriGzZKS0ueUWRd77k3THlxXMHTBc9ugtrlYc2lvBmzy88HyMERV7OKciWtnMaCoV9DiN0Ha7GjoSXfPggiIOOHAsjD3IFfORznRiNKcn6ahj7h28FmmNo="
    on_success: always # default: change
    on_failure: always # default: always